"""add resume path to user

Revision ID: 31768da18ec4
Revises: ccf77ad9cf8b
Create Date: 2026-03-08 01:45:28.828374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31768da18ec4'
down_revision = 'ccf77ad9cf8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('resume_path')

    # ### end Alembic commands ###
