"""added drive_name to placement_drive

Revision ID: 797a4bd2e808
Revises: 
Create Date: 2026-03-02 19:04:20.035336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '797a4bd2e808'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placement_drive', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drive_name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placement_drive', schema=None) as batch_op:
        batch_op.drop_column('drive_name')

    # ### end Alembic commands ###
