"""add ctc column to placement_drive

Revision ID: be6ad1182065
Revises: adefd0581fe0
Create Date: 2026-03-05 20:35:45.538309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be6ad1182065'
down_revision = 'adefd0581fe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placement_drive', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ctc', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placement_drive', schema=None) as batch_op:
        batch_op.drop_column('ctc')

    # ### end Alembic commands ###
