"""ctc not nullable

Revision ID: ccf77ad9cf8b
Revises: be6ad1182065
Create Date: 2026-03-05 20:40:08.869858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccf77ad9cf8b'
down_revision = 'be6ad1182065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placement_drive', schema=None) as batch_op:
        batch_op.alter_column('ctc',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placement_drive', schema=None) as batch_op:
        batch_op.alter_column('ctc',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
